### ISSUE TITLE
Sleeper+ spams the console with dozen of [WARN]'s

### ISSUE THREAD

**Issue by bloodyeyesblackblood** [hraponssi/Sleeper#1]
Hej, I have this (Warning) in the console non-Stop, it spams it every second 20+ times.
After a time the server begins to lag because of this 😅
![image](https://user-images.githubusercontent.com/108025342/208672485-4fc79398-750b-4eec-b19b-97f1aa3c8efc.png)

Is this of the Plugin or do I miss something? an extra File/Plugin for it?
Or os this because I use a Paper server?

**Comment by hraponssi** [comment]
Thanks for the report, looks like I had hardcoded the world name and your server doesn't have a world called the default "world" that I was using. 
I've [uploaded a fix ](https://www.spigotmc.org/resources/sleeper.102406/update?update=482706)and will try to get another version out soon that has better support for custom worlds, for now this will fix the warnings though. :)

**Comment by bloodyeyesblackblood** [comment]
thanks, gonna test it, also yah really funny I def. don't have a World named World I think I renamed it years ago and compl. forgot about it!

Seems like no errors at the time, works great so far and the (1/2) Players Sleeping is also fixed, before it said NaN ^^
