### ISSUE TITLE
implement Sleeper as a MODDED FABRIC version too (server-side)

### ISSUE THREAD

**Issue by Legendmanj** [hraponssi/Sleeper#11]
Would really appreciate it if the plugin also can be used for fabric 1.20.6 server as the features present in it is really awesome. Would love to have it on fabric servers such as mine.
Thank-you

**Comment by hraponssi** [comment]
While this is something I would like to do I don't see it happening any time soon, as I don't do mod development for Fabric or Forge. If someone else wants to they are welcome to, as the project is GPL licensed. I'll close this issue as it goes outside the scope of the bukkit/spigot plugin.
