### ISSUE TITLE
/sleep subcommands work but no /sleep command to trigger sleeping

### ISSUE THREAD

**Issue by SavageTheUnicorn** [hraponssi/Sleeper#12]

**Comment by hraponssi** [comment]
I'm not sure what you mean, as you've given no description of what you are doing and what you expect to happen. If you mean the /sleep command should trigger a night skip that isn't part of the plugin. The closest is by enabling voting to skip the night, and enabling "StartWithoutSleep" so you can start a vote without entering a bed.

**Comment by SavageTheUnicorn** [comment]
Paired with an alias plugin, I got this working great with just /sleep instead of /sleep yes

**Comment by hraponssi** [comment]
Ah I see what you mean now, good that you got it working!
