### ISSUE TITLE
Plugin not working.

### ISSUE THREAD

**Issue by derbygamer03** [hraponssi/Sleeper#13]
I am trying to load the latest version of the plugin with a 1.21 bukkit server but every time i load it it fails to load the plugin

**Comment by hraponssi** [comment]
If you are using just basic craftbukkit the plugin unfortunately won't load because it relies on some chat APIs from Spigot for clickable messages in voting. You'll have to use either Spigot or a varient of it such as [Paper](https://papermc.io/downloads/paper).
