### ISSUE TITLE
Suggestion: Add the ability to enable ignore mode for another player, and by console

### ISSUE THREAD

**Issue by LKirillK** [hraponssi/Sleeper#18]
Add the ability to execute a command for another player
It is necessary that the command can be executed in the server console
 /sleep ignore %player%
It will also help for integration with afk plugins.

**Comment by hraponssi** [comment]
Good suggestion! I'll try to get this added in the coming days.

**Comment by hraponssi** [comment]
This is now implemented in 1.6.2. I also added the extra option to force a player to be ignored or unignored, which might be more reliable for scripting. So `/sleep ignore <Player> <True/False>`
