### ISSUE TITLE
New feature: Skip Night Voting

### ISSUE THREAD

**Issue by hilltty** [hraponssi/Sleeper#2]
The bottom line is that while someone goes to bed, 2 buttons are sent to the chat: "for the pass" and "against the pass", after the specified time in the config, the calculation will be performed, for which more people voted for it, it will be done, so  I suggest doing nothing if, for example, less than 30% of the players voted (you can also add a setting to the config)

**Comment by hraponssi** [comment]
Interesting idea, I'll look into it when I've got time.

**Comment by hraponssi** [comment]
Added in version 1.4.0.
