### ISSUE TITLE
Bug: successful night skip sends the wrong message

### ISSUE THREAD

**Issue by hilltty** [hraponssi/Sleeper#3]
As for me, it would be more logical to send not the message "SleepInfo" after the skip, but some separate message like "Night successfully skipped"

**Comment by hraponssi** [comment]
"SleepInfo" is sent every time a player leaves or enters a bed, and "NightSkip" is sent if the night is skipped. Do you mean you'd want "SleepInfo" not to be sent when leaving the bed after a skip?

**Comment by hilltty** [comment]
as for me, the message should only be sent when the person got out of bed, but the night was not skipped, if it is not, then there is no need

**Comment by hraponssi** [comment]
Fixed in 1.3.2
