### ISSUE TITLE
Calculation for player sleeping percentage wrong?

### ISSUE THREAD

**Issue by ohste** [hraponssi/Sleeper#4]
Tried to use this on a server with 4 people and had the sleep percentage set to 25%. The plugin wouldn't register to skip the night unless all 4 people were asleep. The messages said that 0% of people sleeping. I think the calculation in the number of people sleeping might be off because of using ints rather than doubles. If 1/4 people are sleeping, with ints it would round down to 0. Could be wrong about that but that was the issue I was running into.

**Comment by hraponssi** [comment]
Thanks, good spot! Looks like I broke the calculation when adding support for multiple worlds, fixed now in 1.3.3.
