### ISSUE TITLE
How can you skip night with a vote?

### ISSUE THREAD

**Issue by bipedd** [hraponssi/Sleeper#7]
<img width="633" alt="image" src="https://user-images.githubusercontent.com/77213949/227705258-90429e55-3b20-497b-8473-e46a716898a6.png">
I do /sleep and it doesn't work, if I do /sleep yes it does the same thing. Very confused

**Comment by hraponssi** [comment]
Have you enabled the voting in the config? You need to set the "VoteSkip" config option to true. When it's enabled you'll need to have someone enter a bed to start a vote.

**Comment by bipedd** [comment]
Ah I got it, is it possible to add a configuration setting to make it so that you are not required to sleep in a bed and just doing /sleep can start the vote, also a way to limit one vote per night?

**Comment by hraponssi** [comment]
I released version 1.4.3 with config option "StartWithoutSleep" which allows starting votes without sleeping. Votes should also already be limited to one per world per night.
