### ISSUE TITLE
Sleep Ignore not working

### ISSUE THREAD

**Issue by AlexSkeleton12** [hraponssi/Sleeper#9]
I am in spectator mode and I have ignored myself but it still counts me. I have done the command multiple times and have reset the plugin too. Please fix this.

**Comment by AlexSkeleton12** [comment]
I turns out it only works if im in spectator.

**Comment by hraponssi** [comment]
From a quick test /ignoresleep works for me in spectator and survival mode. Are you in the same world as where the sleeping is taking place? The sleep counts are per world so e.g. nether & end won't count.

Can you test if you can get the issue without other plugins installed, or check if there are any errors in the console?

**Comment by hraponssi** [comment]
Since it's been two weeks without any updates I'll close the issue. If you do still have the issue leave a comment and I'll reopen it.
